export const mission = [
  {
    id: 1,
    name: "Lunar Explorer I",
    launchDate: "2027-03-12",
    status: "Success",
    rocketId: 1,
    crewIds: [1, 2],
    launchPad: "LC-39A",
    destination: "Moon",
    description: "First lunar research mission.",
    image: "https://picsum.photos/400/250?1",
  },
  {
    id: 2,
    name: "Mars Pathfinder",
    launchDate: "2028-07-18",
    status: "Upcoming",
    rocketId: 2,
    crewIds: [3, 4],
    launchPad: "SLC-40",
    destination: "Mars",
    description: "Long-range Mars exploration mission.",
    image: "https://picsum.photos/400/250?2",
  },
  {
    id: 3,
    name: "Europa Survey",
    launchDate: "2026-11-01",
    status: "Failure",
    rocketId: 3,
    crewIds: [],
    launchPad: "LC-39B",
    destination: "Europa",
    description: "Probe deployment mission.",
    image: "https://picsum.photos/400/250?3",
  },
];

export const rocket = [
  {
    id: 1,
    name: "Falcon X",
    firstFlight: "2022-01-10",
    height: 70,
    diameter: 4,
    mass: 549000,
    payloadCapacity: 22800,
    costPerLaunch: 62000000,
    successRate: 98,
    active: true,
    description: "Reusable heavy-lift rocket.",
  },
  {
    id: 2,
    name: "Star Voyager",
    firstFlight: "2025-05-12",
    height: 120,
    diameter: 9,
    mass: 1300000,
    payloadCapacity: 100000,
    costPerLaunch: 150000000,
    successRate: 92,
    active: true,
    description: "Interplanetary transport vehicle.",
  },
  {
    id: 3,
    name: "Titan Nova",
    firstFlight: "2021-09-20",
    height: 85,
    diameter: 5,
    mass: 700000,
    payloadCapacity: 35000,
    costPerLaunch: 90000000,
    successRate: 89,
    active: false,
    description: "Retired exploration rocket.",
  },
];

export const crew = [
  {
    id: 1,
    name: "Emma Carter",
    agency: "NASA",
    status: "Active",
    missions: [1],
    experience: 12,
    image: "https://picsum.photos/300/300?11",
  },
  {
    id: 2,
    name: "James Walker",
    agency: "ESA",
    status: "Active",
    missions: [1],
    experience: 8,
    image: "https://picsum.photos/300/300?12",
  },
  {
    id: 3,
    name: "Sophia Lee",
    agency: "NASA",
    status: "Training",
    missions: [2],
    experience: 4,
    image: "https://picsum.photos/300/300?13",
  },
  {
    id: 4,
    name: "Alex Rodriguez",
    agency: "JAXA",
    status: "Training",
    missions: [2],
    experience: 6,
    image: "https://picsum.photos/300/300?14",
  },
];

export const planedmission = [
  {
    id: 101,
    missionName: "Venus Research Mission",
    destination: "Venus",
    rocketId: 2,
    crewSize: 6,
    launchDate: "2029-04-12",
    objective: "Atmospheric Study",
    budget: 450000000,
    duration: "18 Months",
    status: "Draft",
  },
  {
    id: 102,
    missionName: "Titan Colony Setup",
    destination: "Titan",
    rocketId: 1,
    crewSize: 12,
    launchDate: "2031-08-20",
    objective: "Base Construction",
    budget: 950000000,
    duration: "3 Years",
    status: "Scheduled",
  },
];
